// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPublicCountryHandlerFunc turns a function with the right signature into a get public country handler
type GetPublicCountryHandlerFunc func(GetPublicCountryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPublicCountryHandlerFunc) Handle(params GetPublicCountryParams) middleware.Responder {
	return fn(params)
}

// GetPublicCountryHandler interface for that can handle valid get public country params
type GetPublicCountryHandler interface {
	Handle(GetPublicCountryParams) middleware.Responder
}

// NewGetPublicCountry creates a new http.Handler for the get public country operation
func NewGetPublicCountry(ctx *middleware.Context, handler GetPublicCountryHandler) *GetPublicCountry {
	return &GetPublicCountry{Context: ctx, Handler: handler}
}

/* GetPublicCountry swagger:route GET /public/country/{address} public getPublicCountry

Get country assigned to Etherium address

*/
type GetPublicCountry struct {
	Context *middleware.Context
	Handler GetPublicCountryHandler
}

func (o *GetPublicCountry) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPublicCountryParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
