// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetPublicCountryParams creates a new GetPublicCountryParams object
//
// There are no default values defined in the spec.
func NewGetPublicCountryParams() GetPublicCountryParams {

	return GetPublicCountryParams{}
}

// GetPublicCountryParams contains all the bound params for the get public country operation
// typically these are obtained from a http.Request
//
// swagger:parameters getPublicCountry
type GetPublicCountryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  Min Length: 42
	  In: path
	*/
	Address string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetPublicCountryParams() beforehand.
func (o *GetPublicCountryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAddress, rhkAddress, _ := route.Params.GetOK("address")
	if err := o.bindAddress(rAddress, rhkAddress, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAddress binds and validates parameter Address from path.
func (o *GetPublicCountryParams) bindAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Address = raw

	if err := o.validateAddress(formats); err != nil {
		return err
	}

	return nil
}

// validateAddress carries on validations for parameter Address
func (o *GetPublicCountryParams) validateAddress(formats strfmt.Registry) error {

	if err := validate.MinLength("address", "path", o.Address, 42); err != nil {
		return err
	}

	return nil
}
