// Code generated by go-swagger; DO NOT EDIT.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IdentityResponse identity response
//
// swagger:model IdentityResponse
type IdentityResponse struct {

	// Country
	Country string `json:"Country,omitempty"`

	// Username
	Username string `json:"Username,omitempty"`

	// Etherium address
	EthAddress string `json:"eth_address,omitempty"`
}

// Validate validates this identity response
func (m *IdentityResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this identity response based on context it is used
func (m *IdentityResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IdentityResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdentityResponse) UnmarshalBinary(b []byte) error {
	var res IdentityResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
