// Code generated by go-swagger; DO NOT EDIT.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SetIdentityRequest set identity request
//
// swagger:model SetIdentityRequest
type SetIdentityRequest struct {

	// Country
	// Required: true
	// Min Length: 2
	Country *string `json:"country"`

	// Etherium address
	// Required: true
	// Min Length: 8
	EthAddress *string `json:"eth_address"`
}

// Validate validates this set identity request
func (m *SetIdentityRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCountry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEthAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SetIdentityRequest) validateCountry(formats strfmt.Registry) error {

	if err := validate.Required("country", "body", m.Country); err != nil {
		return err
	}

	if err := validate.MinLength("country", "body", *m.Country, 2); err != nil {
		return err
	}

	return nil
}

func (m *SetIdentityRequest) validateEthAddress(formats strfmt.Registry) error {

	if err := validate.Required("eth_address", "body", m.EthAddress); err != nil {
		return err
	}

	if err := validate.MinLength("eth_address", "body", *m.EthAddress, 8); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this set identity request based on context it is used
func (m *SetIdentityRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SetIdentityRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetIdentityRequest) UnmarshalBinary(b []byte) error {
	var res SetIdentityRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
