// Code generated by go-swagger; DO NOT EDIT.

package private

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"identityserver/pkg/models/rest"
)

// GetPrivateIdentityHandlerFunc turns a function with the right signature into a get private identity handler
type GetPrivateIdentityHandlerFunc func(GetPrivateIdentityParams, *rest.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPrivateIdentityHandlerFunc) Handle(params GetPrivateIdentityParams, principal *rest.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetPrivateIdentityHandler interface for that can handle valid get private identity params
type GetPrivateIdentityHandler interface {
	Handle(GetPrivateIdentityParams, *rest.Principal) middleware.Responder
}

// NewGetPrivateIdentity creates a new http.Handler for the get private identity operation
func NewGetPrivateIdentity(ctx *middleware.Context, handler GetPrivateIdentityHandler) *GetPrivateIdentity {
	return &GetPrivateIdentity{Context: ctx, Handler: handler}
}

/* GetPrivateIdentity swagger:route GET /private/identity private getPrivateIdentity

View identity after it was seted

*/
type GetPrivateIdentity struct {
	Context *middleware.Context
	Handler GetPrivateIdentityHandler
}

func (o *GetPrivateIdentity) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPrivateIdentityParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *rest.Principal
	if uprinc != nil {
		principal = uprinc.(*rest.Principal) // this is really a rest.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
